# .streamlit/secrets.toml
[connections]
db_host = "192.168.0.24"
db_port = "5432"
db_name = "blue_raw"
db_user = "postgres"
db_password = "blsks26"
db_schema = "trusted"

[admin]
password = "admin123"  # Mude para uma senha forte!

[security]
secret_key = "blsks26"
session_expiry = 86400