# .streamlit/secrets.toml
[connections]
db_host = "hayabusa.proxy.rlwy.net"
db_port = "12440"
db_name = "railway"
db_user = "postgres"
db_password = "pLdtmXrUGVCxLeEOZymkgbncAbvmagJI"
db_schema = "trusted"

[admin]
password = "admin123"  # Mude para uma senha forte!

[security]
secret_key = "blsks26"
session_expiry = 86400
